second homework first commit
GustavsIT/homeworks pull request #2
Opened 2023-05-11 10:44 UTC by GustavsIT

2023-05-12 08:27 UTC, GustavsIT commented
Pamaniju, ka ir kaut kads sql import viena vietā, jo rakstiju sout bet sajaucu kaut ko un pielikas klat automatiski laikam.

2023-05-14 05:24 UTC, janistumpelis requested changes
Paldies, nomaini switch uz jauno sintaksi un pielabo to if, pārējais ir labi 👍

2023-05-14 05:24 UTC, janistumpelis commented on src/main/java/io/codelex/flowcontrol/practice/PhoneKeyPad.java
> +            switch (letterDigit) {
Šito pārtaisi par new style switch. Man liekas IDEA jau piedāvā to izdarīt - tā būs stipri īsāk.

2023-05-14 05:24 UTC, janistumpelis commented on src/main/java/io/codelex/flowcontrol/practice/PrintDayInWord.java
> +        switch (number) {
Te arī izmanto jauno switch.

2023-05-14 05:24 UTC, janistumpelis commented on src/main/java/io/codelex/loops/practice/Piglet.java
> +                System.out.println("You rolled a " + randomNumber + " !");
Šī rindiņa varētu būt pirms IF, tad viņa beūs jāatkārto gan IF, gan ELSE

2023-05-15 08:39 UTC, GustavsIT commented
https://github.com/GustavsIT/homeworks/pull/3 ieliku seit ka jaunu comitu

2023-06-04 18:31 UTC, janistumpelis commented
Šito MR vari tad vērt ciet un nemērdžot.

2023-06-06 11:57 UTC, closed without merging